# Generated by Django 2.0.2 on 2018-02-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='thumb',
            field=models.ImageField(blank=True, default='defaut.jpg', null=True, upload_to=''),
        ),
    ]
