# Generated by Django 2.0.2 on 2018-02-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='thumb',
            field=models.ImageField(blank=True, default='defaut.png', null=True, upload_to=''),
        ),
    ]
