# Generated by Django 2.0.2 on 2018-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180223_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='thumb',
            new_name='ID Card',
        ),
        migrations.AddField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, default='defaut.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Others', max_length=6),
        ),
    ]
