# Generated by Django 2.0.2 on 2018-03-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_student_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='designation',
            field=models.CharField(default='Member', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='facebook',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
    ]
