# Generated by Django 2.0.2 on 2018-03-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180325_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='membership',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student Executive Member', 'Student Executive Member'), ('Member', 'Member')], default='Member', max_length=20),
        ),
    ]
