# Generated by Django 2.0.2 on 2018-03-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_student_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ID Card',
            new_name='id_card',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Photo',
            new_name='photo',
        ),
    ]
