# Generated by Django 2.0.2 on 2018-03-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180325_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Member',
        ),
    ]
