# Generated by Django 2.0.2 on 2018-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20180330_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_card',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
