# Generated by Django 2.0.2 on 2018-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20180330_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='course',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='roll',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
