# Generated by Django 2.1 on 2018-08-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20180413_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='transaction_id',
            field=models.CharField(default='NO Transaction ID provided', max_length=25),
        ),
    ]
